# Generated by Django 3.0.2 on 2020-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('branch', models.CharField(default='', max_length=255)),
                ('backGroundPhoto', models.ImageField(upload_to='media/')),
                ('littleSummary', models.TextField()),
                ('smallDescription', models.TextField()),
                ('longDescription', models.TextField()),
                ('firstPhoto', models.ImageField(upload_to=None)),
                ('secondPhoto', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('branch', models.CharField(default='', max_length=255)),
                ('backGroundPhoto', models.ImageField(upload_to='media/')),
                ('littleSummary', models.TextField()),
                ('smallDescription', models.TextField()),
                ('longDescription', models.TextField()),
                ('firstPhoto', models.ImageField(upload_to=None)),
                ('secondPhoto', models.ImageField(upload_to=None)),
            ],
        ),
    ]
