# Generated by Django 3.0.2 on 2020-03-29 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='technical',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='social',
            name='backGroundPhoto',
            field=models.ImageField(upload_to='backGround/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='firstPhoto',
            field=models.ImageField(upload_to='first/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='secondPhoto',
            field=models.ImageField(upload_to='second/'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='backGroundPhoto',
            field=models.ImageField(upload_to='backGround/'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='firstPhoto',
            field=models.ImageField(upload_to='first/'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='secondPhoto',
            field=models.ImageField(upload_to='second/'),
        ),
    ]
